string_1 = str('I am from Borisov')
print(string_1[3])
print(string_1[16])
print(string_1[0:6])
print(string_1[0:15])
print(string_1[::2])
print(string_1[::])
print(string_1[::-1])
print(string_1[::-2])
print(string_1.('a'))